README.md
build.sbt
core/shared/src/main/scala/cats/effect/Async.scala
core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/IO.scala
core/shared/src/main/scala/cats/effect/Sync.scala
project/travis-build.sh

Related to https://github.com/typelevel/cats-effect/issues/7

Fixes #7: Scaladoc Improvements

---

build.sbt
core/shared/src/main/scala/cats/effect/Async.scala
core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/LiftIO.scala

Fixes #24: Provide custom @implicitNotFound to help users

---

build.sbt
laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala

This actually reveals that there's an issue with the scaladoc currently.  @alexandru would you mind taking a look?

Added doc task to ci

---

core/shared/src/main/scala/cats/effect/IO.scala
core/shared/src/test/scala/cats/effect/Generators.scala
laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala
laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

See the #32 proposal, this is the PR in case it gets accepted.

Fixes #32: Rename IO.fail to IO.raiseError

---

build.sbt

Some minor build refinements.  Notably, removes simulacrum from the published dependencies (fixes #41).

Minor build improvements

---

build.sbt
core/shared/src/main/scala/cats/effect/Async.scala
core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/IO.scala
laws/js/src/test/scala/cats/effect/IOJSTests.scala
laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala
laws/shared/src/test/scala/cats/effect/IOAsyncTests.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

Implements the idea presented in #58.  Attention @clhodapp!

Simplified IO.shift

---

core/shared/src/main/scala/cats/effect/IO.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

Add fromEither to raise Either[Throwable,A] to IO[A]

---

build.sbt
core/shared/src/main/scala/cats/effect/Async.scala
core/shared/src/main/scala/cats/effect/LiftIO.scala
core/shared/src/main/scala/cats/effect/Sync.scala

Consistent `liftF`s look nice.

Update to cats 1.0.0-RC2

---

build.sbt

So we're MiMa'ing the right version.

Bump base version to 0.7

---

build.sbt
core/shared/src/main/scala/cats/effect/Async.scala
core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/IO.scala
core/shared/src/main/scala/cats/effect/LiftIO.scala
core/shared/src/main/scala/cats/effect/Sync.scala

Switch traits to abstract classes for better bincompat

---

core/shared/src/main/scala/cats/effect/IO.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

Add SemigroupK instance for IO

---

build.sbt
core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/IO.scala
laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala
laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala
laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala
laws/shared/src/test/scala/cats/effect/LTask.scala

Add Effect#runSyncStep

---

core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
core/shared/src/main/scala/cats/effect/internals/Canceled.scala
core/shared/src/test/scala/cats/effect/concurrent/SemaphoreTests.scala

Added Semaphore

---

core/shared/src/main/scala/cats/effect/concurrent/Ref.scala
core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
core/shared/src/test/scala/cats/effect/concurrent/DeferredTests.scala
core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala

As per [this](https://github.com/typelevel/cats-effect/pull/204#issuecomment-388805220)

`modifyAndReturn` -> `modify`, `modify` -> `modify_`

---

site/src/main/tut/datatypes/io.md

Hi, I figured these docs could be improved. It took me a while to find how to do this.
What do you think, any suggestions on the wording ?

add some docs for parSequence and parTraverse

---

build.sbt
core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala
core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/IO.scala
core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala
core/shared/src/main/scala/cats/effect/concurrent/MVar.scala
core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
core/shared/src/test/scala/cats/effect/concurrent/DeferredTests.scala
core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala
core/shared/src/test/scala/cats/effect/concurrent/SemaphoreTests.scala
laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala
laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala
laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala
laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala
laws/shared/src/test/scala/cats/effect/LTask.scala

addresses the ability to use any Effect with an IOApp in #213.
More comments in #219

Add toIO to Effect

---

core/shared/src/main/scala/cats/effect/concurrent/MVar.scala
core/shared/src/main/scala/cats/effect/internals/MVarAsync.scala
core/shared/src/main/scala/cats/effect/internals/MVarConcurrent.scala
core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala

Here is a PR to add the tryPut, tryTake and isEmpty methods to MVar.
I think we want these for many use cases.

Add try methods to MVar

---

site/src/main/tut/concurrency/ref.md

the return value of modify are reversed

Fix issue on documentation for Ref

---

site/src/main/tut/concurrency/deferred.md

Redundant Parallel in `Deferred` docs

---

site/src/main/resources/microsite/data/menu.yml
site/src/main/tut/datatypes/index.md
site/src/main/tut/datatypes/syncio.md

Let me know if there's something else you think it should definitely be in the microsite for `SyncIO` :smiley:

Docs for SyncIO

---

README.md

After the given feedback on #301 I though it would be nice to have this section in the README file as well as in the microsite's home.

Added Related projects section

---

core/shared/src/test/scala/cats/effect/concurrent/ExitCodeTests.scala
laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

There were several tests that were actually not executing. In fact, it turns out one of them is failing (so this build will fail, but that's what this PR achieves so it should probably be merged regardless)

Make sure properties in tests execute

---

site/src/main/tut/datatypes/io.md

Fixes #327 
Any suggestions welcome.

 Update Concurrency and Cancellation Documentation

---

core/js/src/main/scala/cats/effect/internals/IOAppPlatform.scala

Supports a graceful shutdown of a Node.js process, as opposed to a hard exit.  This should be equivalent to the current behavior on success, but permits a more graceful failure.
https://nodejs.org/api/process.html#process_process_exit_code

Support graceful cleanup in JS by setting process.exitCode

---

build.sbt

Update to Cats 1.3.0

---

build.sbt

Avoids the bincompat issue of 1.3.0.

Upgrade to cats-1.3.1

---

README.md

- add reference to cats documentation with regards to enabling partial unification

docs: update readme wrt. partial unification

---

site/src/main/resources/microsite/data/menu.yml
site/src/main/tut/concurrency/basics.md

Also reworded awkward sentence

Add Concurrency Basics to menu

---

core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala

Several happy paths are covered in addition to a atomicity-related sad path. #324

Increase test coverage of Ref 

---

core/shared/src/test/scala/cats/effect/internals/LinkedMapTests.scala

going to add some more cases, just wanted to get some early feedback

Add some test cases for LinkedMap

---

build.sbt

Fixes #423. Credit goes to @djneades.

Fix #423: add proper Scala.js source maps, pointing to GitHub repo

---

site/src/main/tut/concurrency/ref.md

Current output example is impossible as there is missing 1 in it

Fix error in the Ref docs

---

core/shared/src/main/scala/cats/effect/Bracket.scala
site/src/main/tut/datatypes/io.md
site/src/main/tut/datatypes/ioapp.md
site/src/main/tut/tutorial/tutorial.md

After the initial discovery, I ran through the site files using `ispell` and found a few more to fix.

various spelling corrections

---

core/js/src/main/scala/cats/effect/internals/IOPlatform.scala
core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala
core/shared/src/main/scala/cats/effect/internals/CancelUtils.scala
core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
core/shared/src/main/scala/cats/effect/internals/IOParMap.scala
core/shared/src/main/scala/cats/effect/internals/IORace.scala
core/shared/src/test/scala/cats/effect/internals/CancelUtilsTests.scala
core/shared/src/test/scala/cats/effect/internals/TestUtils.scala
laws/js/src/test/scala/cats/effect/IOJSTests.scala
laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala
laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

Log as a last resort.
Fixes #452

Avoid Throwable#addSuppressed & CompositeException

---

laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala

Suspend vars in SyncLaws

---

site/src/main/tut/datatypes/io.md

Remove redundant brace

---

core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala

Fix infinitely waiting cancellation of a bracket which failed to acquire. Fixes #487

---

core/shared/src/main/scala/cats/effect/Resource.scala

I'm not sure there is a nice way to build a `Bracket` instance, but there is an obvious, and rather useful, `LiftIO`.

Add LiftIO instance for Resource

---

core/shared/src/main/scala/cats/effect/Effect.scala
core/shared/src/main/scala/cats/effect/LiftIO.scala

As proposed by @Daenyth in #465.

Add LiftIO.liftK, Effect.toIOK

---

laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala
laws/shared/src/test/scala/cats/effect/LTask.scala
laws/shared/src/test/scala/cats/effect/SyncIOTests.scala

Remove unused ec in tests

---

site/src/main/tut/datatypes/resource.md

Clear up Resource docs

---

README.md

Add Cats STM to list of related projects

---

site/src/main/tut/datatypes/syncio.md

fix broken sentence in syncio doc

fix broken sentence

---

core/shared/src/main/scala/cats/effect/Concurrent.scala
laws/shared/src/test/scala/cats/effect/MemoizeTests.scala

Concurrent.memoize is well behaved under cancelation

---

core/shared/src/main/scala/cats/effect/Blocker.scala
core/shared/src/main/scala/cats/effect/ContextShift.scala

Review comments from @kubukoz addressed

Renamed ContextShift#evalOn(Blocker) to blockOn and changed Blocker to a value class

---

core/shared/src/main/scala/cats/effect/IO.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

MonoidK instance for IO.Par

---

core/shared/src/main/scala/cats/effect/Async.scala

Currently lifting `F[Future[A]]` to `F[A]` requires `ContextShift[IO]`. This remedies that by exposing the same logic used by `IO.fromFuture` for any `Async`
Closes #563

Add Async.fromFuture (#563)

---

core/shared/src/main/scala/cats/effect/SyncIO.scala

Should fix #529 
Before: 
```scala
scala> def safe: Unit = SyncIO.unit.guarantee(SyncIO.unit).unsafeRunSync
safe: Unit
scala> def broken = SyncIO.unit.bracket(_ => SyncIO(safe))(_ => SyncIO.unit)
broken: cats.effect.SyncIO[Unit]
scala> broken.unsafeRunSync
java.lang.UnsupportedOperationException: cannot synchronously await result on JavaScript; use runAsync or unsafeRunAsync
...
```
After:
```scala
scala> def safe: Unit = SyncIO.unit.guarantee(SyncIO.unit).unsafeRunSync
safe: Unit
scala> def broken = SyncIO.unit.bracket(_ => SyncIO(safe))(_ => SyncIO.unit)
broken: cats.effect.SyncIO[Unit]
scala> broken.unsafeRunSync
scala>
```

Don't create async boundaries for SyncIO#bracket

---

README.md

I think it's useful to have this information on the home page.

add cats-effect-testing to readme

---

site/src/main/mdoc/tutorial/tutorial.md

Fix typo in the tutorial

---

core/shared/src/main/scala/cats/effect/Clock.scala

This makes it possible to derive `Clock` in a monad transformer from `Timer` in the underlying effect, e.g. `Clock[OptionT[F, *]]` from `Timer[F]`.
Currently this is impossible, because the derivation can go either via `Timer[OptionT[F, *]]` or via `Clock[F]`. This change prioritises the former, removing the ambiguity.

Remove ambiguity in Clock derivation

---

core/jvm/src/main/scala/cats/effect/internals/BlockerPlatform.scala

Resolves #692. 
I _think_ this is the most minimal way to fix the problem.

Wrap default Blocker EC with exitOnFatal.

---

core/jvm/src/main/scala/cats/effect/internals/BlockerPlatform.scala
core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala

#710 Indexed blocker thread names JVM

---

README.md

https://github.com/valskalla/odin/
>Odin library enables functional approach to logging in Scala applications with reasoning and performance as the top priorities.
>
>- Each effect is suspended within the polymorphic F[_]
>- Context is a first-class citizen. Logger is structured by default, no more TheadLocal MDCs
>- Programmatically configurable. Scala is the perfect language for describing configs
>- Position tracing implemented with macro instead of reflection considerably boosts the performance
>- Own performant logger backends for console and log files
>- Composable loggers to bring different loggers together with Monoid[Logger[F]]
>- Backend for SLF4J API
>
> Standing on the shoulders of cats-effect type classes, Odin abstracts away from concrete effect types,  allowing users to …

Add Odin to related projects table

---

core/shared/src/main/scala/cats/effect/Resource.scala
laws/shared/src/main/scala/cats/effect/laws/discipline/arbitrary.scala
laws/shared/src/main/scala/cats/effect/laws/util/TestInstances.scala
laws/shared/src/test/scala/cats/effect/ResourceTests.scala

First prototype for parallel resource acquisition.
Please only look at the implementation, I intend to expose this as a `Parallel` instance rather than the `parZip` function. 
Needs proper testing as well

Parallel resource

---

site/src/main/mdoc/datatypes/io.md

This fixes a layout and compiler error problem with a code block (cancellability of  non-terminating IO) on https://typelevel.org/cats-effect/datatypes/io.html

Fixed layout/code problem in doc for IO

---

core/shared/src/main/scala/cats/effect/internals/IOConnection.scala
laws/shared/src/test/scala/cats/effect/IOTests.scala

Fix bug when double cancelation would hang second cancel

---

core/shared/src/main/scala/cats/effect/Concurrent.scala
laws/shared/src/test/scala/cats/effect/ConcurrentContinualTests.scala

Fix `continual` hanging when canceled really fast

---

core/js/src/main/scala/cats/effect/internals/IOAppPlatform.scala

Fixes #809 
Disclaimer: I don't use scala.js, haven't written serious JavaScript in a decade, and am utterly unqualified to be working on this side of the house.

Remove sys.exit calls on JS runtime

---

core/shared/src/main/scala/cats/effect/Concurrent.scala

I copied the example to learn how to use this function and noticed it was not compiling :)

Minor documentation fix in Concurrent.cancelableF

---

site/src/main/mdoc/concurrency/basics.md

See: #826 for brief explanation.

#826 Blocking example updated to use Blocker

---

site/src/main/mdoc/datatypes/ioapp.md
site/src/main/mdoc/tutorial/tutorial.md

Add warnings to docs about IOApp cancelation issues within sbt.

---

core/shared/src/main/scala/cats/effect/Blocker.scala

Some explanation found in gitter like this one:
https://gitter.im/typelevel/cats-effect?at=5d87a3962438b53a64fa7a7c

Add some motivation for explicit Blocker
