.gitignore, core/jvm/src/main/scala/cats/effect/IOPlatform.scala, core/jvm/src/test/scala/cats/effect/IOJVMTests.scala
The original implementation does not use Scala's [BlockContext](http://www.scala-lang.org/api/current/scala/concurrent/BlockContext.html).
I know that the original rationale for providing `unsafeRunSync` is that this method should be executed at the "*edge of the program*", however that differs from user to use ... e.g. if somebody uses Play Framework, the edge of the program might be the end of the controller `Action`.
Users are also unpredictable. You might preach to them that they should describe whole pure programs as `IO` through composition and then evaluate that only once in `main`, however the fact is that many users won't do that.
Using Scala's `BlockContext` has the benefit that it instructs the underlying thread-pool (if there is one that is listening) to take defensive …
=> Improve the JVM blocking in IOPlatform

laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
We can add a the weakened version of the law (as suggested by @alexandru in #15) if we think there is value in that.  For the time being, I just removed the law and added a corresponding test on `IO`.
=> Remove "throw in register" law to avoid over-constraining impls

.travis.yml, README.md, build.sbt, core/jvm/src/test/scala/cats/effect/IOJVMTests.scala, project/plugins.sbt, project/travis-build.sh, project/travis-post-build.sh
Configuring Codecov.io
- in my experience `sbt-scoverage` is dirty, attaches itself to the generated POM, had problems with Scala 2.12, etc
- therefore I chose to enable coverage in builds only when required, by passing `-Dsbt.profile=coverage` to the `sbt` command
- in Travis coverage is measured and uploaded only for a `MAIN_SCALA_VERSION` configured in `.travis.yml`
=> Fixes #11: Configure sbt-scoverage + Codecov.io for test coverage

laws/js/src/test/scala/cats/effect/IOJSTests.scala, laws/shared/src/test/scala/cats/effect/IOAsyncTests.scala
Added a new `IOAsyncTests` that execute for both the JVM and JS, piggybacking on ScalaTest's async stuff.
=> Fixes #23: tests for runAsync

core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestInstances.scala, laws/shared/src/test/scala/cats/effect/BaseTestsSuite.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
~~This is a proposal to rename `fromFuture` to `deferFuture`.~~
Scala is by default an eager language, which is why one of the first WTFs of people learning Scalaz is in noticing that by-name parameters are used everywhere. And then the second WTF you have is when moving from Scalaz to Cats and noticing that everything is eager by default, as it should be, since this is Scala.
The most obvious example is `Applicative.pure`, which in Cats takes an eager parameter. Now this is problematic because the lazy by-name variant doesn't exist yet, but given that this is Scala, having an eager `pure` makes a lot of sense and avoids a lot of gotchas.
By-name parameters are problematic in themselves, because changing the code a little, you get a different behavior. This has been the rationale for …
=> Change fromFuture to take a cats.Eval param

build.sbt, core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Effect.scala, laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala
Now, `Async <: Sync`.  The reason for this is it's generally impossible to implement `Effect[F]` for an MTL stack which does not involve exclusively copointed effects.  Which is to say, not a particularly interesting stack.  So most stacks end up implementing both `Sync` and `Async`, but this is a problem because then two `Monad` instances are in scope.  Since it is always possible to suspend `Sync` effects in an `Async` (though not necessarily stack-safely), I think it's somewhat reasonable for the latter to extend the former.  I prefer having them split, but there's nothing for it.
Without this change, the typeclass hierarchy is considerably less useful.
=> Linearized Effect hierarchy

core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/internals/AndThen.scala, core/shared/src/test/scala/cats/effect/internals/AndThenTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
I discovered a weird  space leak that I talked about in https://github.com/typelevel/cats-effect/issues/42#issuecomment-298256710 by debugging the behavior of this law:
```scala
lazy val stackSafetyOnRepeatedAttempts = {
val result = (0 until 10000).foldLeft(F.delay(())) { (acc, _) =>
F.attempt(acc).map(_ => ())
}
F.runAsync(result)(_ => IO.unit).unsafeRunSync() <-> (())
}
```
This PR fixes this space leak by changing the behavior of `IO#attempt`:
- removes the `AndThen.ShortCircuit` logic
- adds the notion of `AndThen.ErrorHandler`, which is meant to process errors
- upon an error being signaled, in the `AndThen` implementation we discard `Single` references until we reach an `ErrorHandler` that can process our error, or until we've got no more `AndThen` nodes to process, in which case …
=> Change IO's run-loop to encode error handlers

core/shared/src/main/scala/cats/effect/Effect.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/test/scala/cats/effect/Generators.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
This is a follow up on https://github.com/typelevel/cats-effect/pull/47
Adding a conversion utility to `IO` that can convert from any type implementing the `Async` type-class:
```scala
def to[F[_]](implicit F: cats.effect.Async[F]): F[A @uV]
```
Notes:
- internal implementation tries to do conversion as efficient as possible, being one raison for why it exists because doing `F.async(io.unsafeRunAsync)` can be inefficient, besides being dangerous
- we are using `@uncheckedVariance` to avoid introducing a `B >: A` type (due to covariance), which would wreck our signature; Scala's standard library also does it for the conversions in the standard collections
=> Add IO#to conversion method

core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Effect.scala, core/shared/src/main/scala/cats/effect/LiftIO.scala, core/shared/src/main/scala/cats/effect/Sync.scala, core/shared/src/test/scala/cats/effect/Generators.scala, laws/js/src/main/scala/cats/effect/laws/discipline/EffectTestsPlatform.scala, laws/jvm/src/main/scala/cats/effect/laws/discipline/EffectTestsPlatform.scala, laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Most notably, this adds `Sync[Eval]`, but we also get a number of other things related to transformer stacks.  Automatic derivation of `Async` in a basic transformer stack is now possible under most circumstances, though the usual caveats around ambiguity remain (since `Async <: Monad`), and automatic derivation of `Effect` is possible under *specific* circumstances.  Specifically: `StateT[F, S, ?]` given `Monoid[S]`, `WriterT` and `EitherT[F, Throwable, ?]` (which it implements by flattening the inner context into the outer).
Closes #48.
=> Lots of convenience instances

laws/shared/src/test/scala/cats/effect/InstancesTests.scala
This is for the Scala community build, which builds masters.  Attention @SethTisue!  Once this lands, you should be able to unfreeze the cats-effect snapshot.
=> Fixed build against cats master

build.sbt, core/shared/src/main/scala/cats/effect/Sync.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Given the removal of `MonadError[Sync, Throwable]`, it seems that something like this would be useful.
=> Added Sync[EitherT[Eval, Throwable, ?]] instance

core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Effect.scala
We forgot about this override when we overrode it in `Async`.
=> Remove Effect.liftIO

core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Sync.scala, laws/js/src/main/scala/cats/effect/laws/discipline/TestsPlatform.scala, laws/jvm/src/main/scala/cats/effect/laws/discipline/TestsPlatform.scala, laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Fixes #52 
Moves stack-safety laws up into `SyncLaws`, as well as some of the error propagation laws.  Also adds a law which stipulates that errors in the `runAsync` handler effect must be discarded (previously this was unspecified).
I had to remove the `Async[Kleisli[F, R, ?]]` instance with the laws moving up, because `Kleisli` is stack-unsafe on left-associated binds (see: https://github.com/typelevel/cats/issues/1733).  This is a shame, but not entirely unexpected.
=> Pull up laws

laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
This law is in my opinion incorrectly defined:
```scala
def propagateErrorsThroughBindSuspend[A](t: Throwable) = {
val fa = F.attempt(F.delay[A](throw t).flatMap(x => F.pure(x)))
fa <-> F.pure(Left(t))
}
```
The problem is that I just implemented `Sync` for an `F` type that is a stream and that emits multiple `A` values. There's nothing in the `Sync` laws that prevent this and I don't see why I shouldn't do it, except for the law above, which indirectly prevents this usage.
The problem is that the given equivalence will not hold, because it's going to end up with something like `List(Right(a), Right(a), Left(e)) <-> List(Left(e))`.
This happens for `raiseError` as well, however in the case of `raiseError` you can clearly bend the `Eq` definition to allow 2 values to be equivalent, even if …
=> Modify SyncLaws to allow types to emit more than one value, thus allowing streams

build.sbt, core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/LiftIO.scala, core/shared/src/main/scala/cats/effect/Sync.scala, laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
Upgrades:
- cats-1.0.0-RC1
- discipline-0.8
- simulacrum-0.11.0
- scalatest-3.0.4
- scalacheck-1.13.5
=> Upgrade to cats-1.0.0-RC1 and more

laws/shared/src/main/scala/cats/effect/laws/discipline/Arbitrary.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
This makes `Arbitrary[IO]` and `Cogen[IO]` available to other projects that depend on cats-effect-laws.
- Repackaged to mirror `cats.laws.discipline.arbitrary`
- Implicits renamed to follow cats guidelines.
Fixes #74.
=> Publish arbitrary instances in cats-effect-laws

build.sbt, core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
`IO.fromFuture` now takes an `IO` (fixes #78). Also change the param name of `IO.eval` so as not to suggest that it could be effectful.
=> IO.fromFuture now takes an IO

README.md
Dear all,
This fixes the broken link to `cats.effect.IO` docs.
-V
=> Fix broken link to cats.effect.IO docs

core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala
Continuing the work started in PR #90, this pull request optimizes `IO.apply`.
We do so by introducing a special internal state just for it. This is worth it in terms of performance because it avoids extraneous memory allocations and the numbers look good.
Also the loops described in `IORunLoop` are now no longer described as `@tailrec` functions, but as `while` loops. This led to a slight improvement across the board and it's important because it afforded us the `IO.apply` optimization in its current form.
Here's the numbers and note that version `0.6-964e8d0` here is PR #90:
| Benchmark |    0.5   |   0.6-964e8d0   |   This PR   |
|:----------|---------:|----------------:|------------:|
| ShallowBindBenchmark.async | 48.609 | 83.134 | 87.018 |
| ShallowBindBenchmark.delay | 1535.69 | …
=> Second Batch of Optimizations — IO.apply

benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapCallsBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapStreamBenchmark.scala, core/js/src/main/scala/cats/effect/internals/IOPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/internals/IOFrame.scala, core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/Arbitrary.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
Third PR addressing performance issues. Previous ones are #90 and #91.
Also addresses issue #92, but without the proposed laws.
---
In order to avoid stack-overflow errors, repeated `.map` calls trigger a `.flatMap` every 128 calls.
The rationale is thus — from my research the default stack size ranges from 320 KB on 32-bits operating systems to 1 MB on 64-bits operating systems. From my own tests a stack frame triggered by a `Function1` chaining consumes aproximately 32 bytes. So 128 fused `map` calls will consume `32 bytes * 128 = 4 KB` at a minimum (to which you add whatever else the user is doing on that stack).
In a real `flatMap` chain, which is what happens with `IO`, the performance does end up being dominated by `.flatMap` calls even with `.map` calls being mixed-in (a benchmark …
=> Third optimization batch — map fusion

core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala
PR adds laws in `SyncLaws`.
This can be coupled with the "map fusion" changes for PR #95 — I've separated it because this PR is about the laws in `SyncLaws`.
The laws we are adding:
1. bind suspends evaluation
2. map suspends evaluation
3. stack-safe on repeated maps
Note the first 2 laws need to take an `fa: F[A]` parameter because we want this suspension of effects regardless of what the source `F[A]` is (`Pure` or not). If we don't do this, then as mentioned in issue #92 the implementation is not stack safe because the passed closure can contain a recursive function call.
I've also changed `IO.ioEffect` because interestingly we weren't overriding `map` or `unit`, so we couldn't see that `IO.map` wasn't suspending the evaluation because it wasn't being used in the tests.
Note that I …
=> Fix #92: Sync.map should suspend evaluation

core/js/src/main/scala/cats/effect/internals/IOPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala, core/shared/src/test/scala/cats/effect/internals/OnceOnlyTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
Fixes #108 by re-throwing thrown exceptions in `IO.async` after the callback was called once.
As I said in [my comment](https://github.com/typelevel/cats-effect/issues/108#issuecomment-355314764):
`IO.async` represents an async communication protocol between a producer and a consumer and unhandled exceptions represent a **protocol violation**, at which point the behavior can be considered to be undefined.
We can agree however that swallowing exceptions with no error reporting is bad. But it's also not correct to do a `printStackTrace` because many web services will just throw $stderr into `/dev/null`, relying on logging libraries like [Logback](https://logback.qos.ch/) to report any errors that happen.
And because `cats.effect.IO` does not have an underlying `Scheduler` or …
=> Fix #108: re-throw exception in IO.async after callback was called once

laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
Fixes #118
I tested the change by attempting to add
```scala
case Pure(a) => try Pure(f(a)) catch { case NonFatal(ex) => RaiseError(ex) }
```
to the implementation of IO#map, and the law check failed as expected.
=> Change check in SyncLaws to allow streaming types

laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala
I'm opening this directly without creating an issue as it looks really trivial. One of the Async laws is not checked.
=> Fixed what looks like to be a typo in the Async laws discipline

benchmarks/shared/src/main/scala/cats/effect/benchmarks/AttemptBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/DeepBindBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/HandleErrorBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapCallsBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapStreamBenchmark.scala, benchmarks/shared/src/main/scala/cats/effect/benchmarks/ShallowBindBenchmark.scala, build.sbt, core/js/src/main/scala/cats/effect/internals/Logger.scala, core/jvm/src/main/scala/cats/effect/internals/Logger.scala, core/shared/src/main/scala/cats/effect/Fiber.scala, core/shared/src/main/scala/cats/effect/internals/Callback.scala, core/shared/src/main/scala/cats/effect/internals/Cancelable.scala, core/shared/src/main/scala/cats/effect/internals/ForwardCancelable.scala, core/shared/src/main/scala/cats/effect/internals/IOCancel.scala, core/shared/src/main/scala/cats/effect/internals/IOConnection.scala, core/shared/src/main/scala/cats/effect/internals/IOFiber.scala, core/shared/src/main/scala/cats/effect/internals/IOStart.scala, core/shared/src/test/scala/cats/effect/internals/BooleanCancelable.scala, core/shared/src/test/scala/cats/effect/internals/CallbackTests.scala, core/shared/src/test/scala/cats/effect/internals/CancelableTests.scala, core/shared/src/test/scala/cats/effect/internals/ForwardCancelableTests.scala, core/shared/src/test/scala/cats/effect/internals/IOConnectionTests.scala, core/shared/src/test/scala/cats/effect/internals/TestUtils.scala, laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala
When I committed the headers change, relied on the plugin to generate headers for all files, but it did not catch all files in its build.
This PR also bumps the `BaseVersion` to `0.10`, so we can do hash releases. It's a zero `0.10` because the current `master` breaks compatibility with the released `0.9`.
=> Add missing headers, bump BaseVersion

core/js/src/main/scala/cats/effect/internals/IOTimer.scala, core/js/src/main/scala/cats/effect/internals/IOTimerRef.scala, core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala, core/jvm/src/main/scala/cats/effect/internals/IOTimerRef.scala, core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/Timer.scala, core/shared/src/main/scala/cats/effect/internals/Callback.scala, core/shared/src/main/scala/cats/effect/internals/IOConnection.scala, laws/js/src/test/scala/cats/effect/internals/IOTimerTests.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala, laws/shared/src/test/scala/cats/effect/IOAsyncTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, laws/shared/src/test/scala/cats/effect/TestContextTests.scala, laws/shared/src/test/scala/cats/effect/TimerTests.scala, laws/shared/src/test/scala/cats/effect/laws/util/TestContextTests.scala
`cats.effect.IO` has one great weakness, with these being the symptoms:
- its reliance on `ExecutionContext` for triggering async boundaries (e.g. `IO.shift`), which makes its API in common use to be in fact impure, because reliance on `ExecutionContext` can affect its referential transparency
- it has no way to schedule execution with a delay (e.g. `Thread.sleep`) without reliance on Java's `ScheduledExecutorService` or on JavaScript's `setTimeout`
- this problem is made worse by Scala not providing its own interface, an analogue to `ExecutionContext` that we could use for delays, with libraries like Monix and FS2 implementing their own `Scheduler` interface
So the answer to that is currently ¯\_(ツ)_/¯
**How does Haskell do it?**
Haskell provides among others:
1. …
=> Add Timer and purify the IO API

core/js/src/main/scala/cats/effect/internals/IOTimer.scala, core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala, core/shared/src/main/scala/cats/effect/Timer.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala, laws/shared/src/test/scala/cats/effect/TestContextTests.scala, laws/shared/src/test/scala/cats/effect/TimerTests.scala
A change discussed in #132, but that didn't make it yesterday, splitting `Timer.currentTime` in two, to avoid confusion with its `tryMonotonic` boolean parameter:
```scala
def clockRealTime(unit: TimeUnit): F[Long]
def clockMonotonic(unit: TimeUnit): F[Long]
```
The names refer to `CLOCK_REALTIME` and `CLOCK_MONOTONIC` from Linux's `clock_gettime()`, which are being used by the JVM when doing `System.currentTimeMillis` and `System.nanoTime` respectively.
=> Split Timer.currentTime in clockMonotonic and clockRealTime

README.md, site/src/main/tut/io.md
The aim of this PR is to:
The final objective is to have a decent / ready documentation in time for the publishing of the version `0.10`.
Suggestions and corrections are welcome.
=> IO documentation for `v0.10`

core/shared/src/main/scala/cats/effect/internals/AndThen.scala, core/shared/src/test/scala/cats/effect/internals/AndThenTests.scala
We used `AndThen` for the `Sync[StateT]` instance.
At this point its future in `cats-effect` is a little uncertain due to https://github.com/typelevel/cats/pull/2187 - however if that PR doesn't make it in Cats, then it will probably continue to live on in `cats-effect`.
This PR introduces the same optimization used for `IO#map`, doing fusion in its `andThen` and `compose` up to a maximum threshold.
=> AndThen optimisation

core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/Sync.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Instances for `cats.data.Kleisli` where initially added but then removed in https://github.com/typelevel/cats-effect/pull/69 due to `Kleisli` not being stack safe for left associative binds.
There is now a still opened issue in the Cats repo at: https://github.com/typelevel/cats/issues/1733
In this commit I'm providing lawful instances with a non-broken `flatMap`, the same thing I did for `StateT`.
However as mentioned in my comment [on that issue](https://github.com/typelevel/cats/issues/1733#issuecomment-371982346), the problem with this solution is that the `Sync` instance now lacks coherence with `Kleisli`'s own Monad implementation.
Therefore the plan is to also push these changes in the Cats repository, as the problem is fixable by essentially triggering the `F[_]` context earlier …
=> Re-add Kleisli instances for Sync, Async and Concurrent

build.sbt, site/src/main/resources/microsite/css/toc.css, site/src/main/resources/microsite/js/toc.js, site/src/main/resources/microsite/layouts/docsplus.html, site/src/main/tut/datatypes/fiber.md, site/src/main/tut/datatypes/io.md, site/src/main/tut/datatypes/timer.md, site/src/main/tut/typeclasses/async.md, site/src/main/tut/typeclasses/bracket.md, site/src/main/tut/typeclasses/concurrent-effect.md, site/src/main/tut/typeclasses/concurrent.md, site/src/main/tut/typeclasses/effect.md, site/src/main/tut/typeclasses/liftio.md, site/src/main/tut/typeclasses/sync.md
The `IO` article is getting pretty long and it's going to get longer.
This PR adds the possibility of adding a table of contents to articles that need it, generated via JavaScript.
Screenshot:
=> Docs: add TOC to IO article

site/src/main/tut/datatypes/io.md
I'm reading docs and encountered small grammar error in IO section.
I also have suggestion to add link to the hierarchy - it is mentioned but it isn't anywhere near and if someone (like me) starts reading docs from the top they will see it much later.
=> Add link to hierarchy in IO doc and fix grammar error

build.sbt, core/shared/src/main/scala/cats/effect/Async.scala, laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala
Commit implements the never helper function inside the async trait and
uses that function in the Companion Object that previously implemented
the same function
This addresses the Issue #141
=> Implement the never helper function

.travis.yml, README.md, build.sbt, laws/shared/src/test/scala/cats/effect/InstancesTests.scala, versioning.md
Should fix #179. Seems like we're close to consensus on this one. I don't think there's anything that's blocking us in 2.10 (I resolved my issue from yesterday), but I'd decided to put this together anyway, we can still not merge this or merge it a later date.
=> Remove 2.10 support

core/shared/src/main/scala/cats/effect/Sync.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
This instance could be used to break referential transparency
in polymorphic code. Fixes #170.
=> Remove Sync instance for EitherT[Eval, Throwable, ?]

core/shared/src/main/scala/cats/effect/IO.scala
If an error happens in the async handler, it gets swallowed without a report.  It's reasonable not to re-raise it (see `EffectLaws.runAsyncIgnoresErrorInHandler`), but this can mask fatal errors without a trace.  For one http4s user, this hid a linker error due to mill putting two versions of cats on the classpath.
This ought to be tested, but I didn't immediately see a cross-platform way, and I wanted to make sure there is agreement on the change before I hurt my brain finding a way.
If we don't want this, we could use `Callback.dummy1`.
=> IO.runAsync should report errors in its handler

laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/Parameters.scala
Related to the changes in PR #168.
The law for `F.never <-> F.async(_ => ())` is causing problems in Monix because `Task` tests the provided laws multiple times depending on the evaluation mode and now we have a `runSyncUnsafe(timeout)` operation, only allowed on the JVM, that blocks the current thread. And the laws are tested with an `Eq` based on it as well, in addition to the regular tests that make use of the fake and safe `TestScheduler`.
Unfortunately when blocking threads the only way to detect non-termination is to block the thread with a timeout.
Changes in this commit:
1. allow for disabling this law via `Params`
2. fix the law to not require an `a: A` param, because it is unused and the result is that the test runs multiple times (due to ScalaCheck generating random `A` values) …
=> Fix AsyncLaws.neverIsDerivedFromAsync, add param for disabling it

laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala
`bracketReleaseCalledForSuccess` in `SyncLaws` is currently broken for streams.
The reason is that in order to *observe* the side effect, it relies on `F.flatMap`, however this particular `F.flatMap` usage assumes sequencing like what happens in `IO` (i.e. execute this, after the source is *done*), but this isn't what happens for streams, where `flatMap` inserts its result for *each element of the source*.
The other problem with this law is that it is incomplete for streaming types.  For `monix.tail.Iterant` we now have this `bracket` method:
```scala
final def bracket[B](use: A => Iterant[F, B])(release: A => Iterant[F, Unit])
(implicit F: Sync[F]): Iterant[F, B] = ???
```
How it works is that `release` happens for each `A`, it's actually implied in the signature and this behavior isn't …
=> Fix Bracket law

core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala, core/shared/src/main/scala/cats/effect/Fiber.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/internals/ForwardCancelable.scala, core/shared/src/main/scala/cats/effect/internals/IOConnection.scala, core/shared/src/test/scala/cats/effect/internals/IOConnectionTests.scala, laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, site/src/main/tut/datatypes/fiber.md, site/src/main/tut/datatypes/io.md, site/src/main/tut/typeclasses/concurrent-effect.md, site/src/main/tut/typeclasses/concurrent.md
* Correct the example for `Concurrent.cancelable`
* Continue standardizing on American spellings
=> Cancellation docs

build.sbt, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/internals/IOFrame.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
This is related to https://github.com/typelevel/cats/pull/2237
This uses `IO`'s internals to expose an optimized `redeemWith` operation, that's equivalent with doing `attempt.flatMap`, but avoiding a second `flatMap` boundary, or extra boxing in `Either`.
The performance improvements on doing this are pretty good, see: https://github.com/typelevel/cats/issues/2161 — and the capability of doing this has been in `IO` ever since I optimized its internal encoding, we just need to expose it.
=> Add IO#redeem and IO#redeemWith

core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/IO.scala
Adds timeoutTo and timeout to enable timeouts for IO and F
per https://github.com/typelevel/cats-effect/issues/209
=> Add timeout for IO and generic F

core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala, core/shared/src/main/scala/cats/effect/concurrent/MVar.scala, core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala, core/shared/src/test/scala/cats/effect/concurrent/DeferredTests.scala, core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala, core/shared/src/test/scala/cats/effect/concurrent/SemaphoreTests.scala
A thing discussed on gitter, a follow-up to now-closed #220.
* `MVar.init` to `MVar.of`.
* `async` suffixes in factory methods are renamed to `uncancelable`. I think this is more intuitive, as word *async* is typically used to indicate something non-blocking, not something non-cancelable. Also, having `MVar.ofAsync(a)` would be quite misleading :)
=> Rename MVar.init to of and async suffix to uncancelable

core/shared/src/main/scala/cats/effect/concurrent/MVar.scala, core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala
Removing `MVar.ofF` and `MVar.uncancelableOfF`, because they are just mapping `F[_]` and I'm not sure if it helps with anything.
In cats-effect it's better if the API surface is smaller. We can reconsider afterwards.
=> Remove MVar.ofF (previous initF)

site/src/main/resources/microsite/data/menu.yml, site/src/main/tut/concurrency/deferred.md, site/src/main/tut/concurrency/index.md, site/src/main/tut/concurrency/mvar.md, site/src/main/tut/concurrency/ref.md, site/src/main/tut/concurrency/semaphore.md, site/src/main/tut/datatypes/index.md
Adding the microsite documentation for the types introduced by #188 and #196 .
Examples for `Deferred` and `Ref` were taken from [fs2 concurrency primitives](https://functional-streams-for-scala.github.io/fs2/concurrency-primitives.html) (which I was the author) and adapted to `Cats Effect`. Note that this is still not compiled through `tut` because the source is yet not merged, I will update this PR once it's done.
Example for `Resource` was taken from the Scala doc and adapted to compile with `tut`.
EDIT: Added docs for `Semaphore` with examples taken from the `fs2` guide as well.
~The typeclasses diagram is now missing the `Resource` typeclass, call for~ @Zelenya :smiley:
=> Documentation for Resource, Deferred, Ref & Semaphore

build.sbt, core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Bracket.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/Sync.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala
This is a first step towards fixing #216: adds a `Bracket` instance for `Kleisli`.
=> Bracket instance for Kleisli

build.sbt, core/js/src/main/scala/cats/effect/internals/IOAppPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/internals/IOBinaryCompat.scala, core/shared/src/main/scala/cats/effect/internals/IOParMap.scala, core/shared/src/main/scala/cats/effect/internals/IORace.scala, core/shared/src/main/scala/cats/effect/internals/IOStart.scala, core/shared/src/test/scala/cats/effect/IOAppTests.scala, core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala, core/shared/src/test/scala/cats/effect/internals/TestUtils.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, site/src/main/tut/concurrency/mvar.md, site/src/main/tut/concurrency/ref.md, site/src/main/tut/concurrency/semaphore.md, site/src/main/tut/datatypes/fiber.md, site/src/main/tut/datatypes/io.md
=> Require Timer and shift automatically in concurrent IO operations

site/src/main/tut/concurrency/semaphore.md
A very small change to docs I missed in #222, when Semaphore.async builder was renamed to Semaphore.uncancelable.
=> Fix: Semaphore.async -> Semaphore.uncancelable in docs

core/js/src/main/scala/cats/effect/internals/IOPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala, core/shared/src/main/scala/cats/effect/internals/IOBracket.scala, laws/js/src/test/scala/cats/effect/IOJSTests.scala, laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala
For `IO.bracket` we are logging the error in `release` in case `use` fails.
This PR changes the implementation such that:
1. on top of the JVM we are using `Throwable#addSupressed`, signaling the error in `use`, but with the error in `release` added as being suppressed
2. on top of JS we are bundling them together with `CompositeException`
```scala
IO.unit.bracket(_ => IO.raiseError(err1))(_ => IO.raiseError(err2))
```
On top of the JVM this piece of code should be equivalent with `IO.raiseError(err1)`, but `err2` is added as a "suppressed" error of `err1`. This is the standard way the JVM now deals with suppressed errors in its try-with-resources construct.
=> Use Throwable#addSupressed when IO.bracket fails in both use and release

core/js/src/main/scala/cats/effect/internals/IOPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala
Fixes `IOPlatform.composeErrors` to ignore duplicate references, or otherwise `addSuppressed` throws exception.
=> Fix IOPlatform.composeErrors

core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/IO.scala
I have to push a fix for `asyncF` — it has the quality of hooking into the underlying cancellation mechanism, however the underlying connection used is current used by both:
- the bind continuation of the generated `asyncF`
- the task generated by the registration function and the `runCancelable` that we are doing
This can create a race condition. It's not easy to reproduce, because we'd need to schedule tasks for execution *after* executing the callback. So a sample like this can screw with the run-loop:
```scala
IO.asyncF { cb =>
IO(cb(Right(())) *> IO.sleep(1.second) *> IO(println("Fire and forget!"))
}
```
=> Fix IO.asyncF

laws/shared/src/main/scala/cats/effect/laws/discipline/Parameters.scala
In tests we are doing `100,000` iterations by default for the stack safety tests.
Even if we can fine tune it, that's too much. Decreasing that default to `10,000`, which is the value we've been using for Travis anyway.
=> Decreasing default stackSafeIterationsCount

laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala
Non-terminating laws (i.e. testing equivalence with `F.never`) cannot be tested in case the evaluation in `Eq` is done via blocking threads (e.g. usage of `unsafeRunSync`).
The `uncancelablePreventsCancelation` law is such a law that needs a comparison with `F.never` and thus needs to be excluded.
=> Exclude non-terminating law from the default tests

laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala
Removing `runSyncStepAsyncNeverProducesLeftPureIO` because:
- it is redundant with `runSyncStepAsyncProducesLeftPureIO`
- it is expensive due to usage of `F.never`, also see recent #260
=> Remove EffectLaws.runSyncStepAsyncNeverProducesLeftPureIO

build.sbt, core/shared/src/main/scala/cats/effect/Resource.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/Arbitrary.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestInstances.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala
As mentioned in PR #270 (see [my comment](https://github.com/typelevel/cats-effect/pull/270#pullrequestreview-133517991)), I believe the current `Resource` encoding isn't sufficient, the current implementation assuming the behavior of `IO`, yet `F[_] : Bracket` assumes no such thing.
In particular if `F[_]` is a stream, then both the current and the proposed `flatMap` implementations are broken.
This PR proposes  a new encoding for `Resource`.
With this new encoding, `Resource` now works much like streaming abstractions do (i.e. it has the ability to interpret `flatMap` calls in a safe way), whereas previous implementations had to rely on `flatMap` for specifying acquisition of combined resources, which is unsafe in the presence of cancellation.
```scala
case class Allocate[F[_], A]( …
```
=> Resource — new encoding

laws/shared/src/test/scala/cats/effect/BaseTestsSuite.scala
procedure syntax is deprecated https://github.com/scala/scala/commit/1d4d901fcea0a162cd139836b246e85cc0130a6b
=> fix procedure syntax

build.sbt, core/js/src/main/scala/cats/effect/internals/IOPlatform.scala, core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala, core/shared/src/main/scala/cats/effect/Fiber.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala, core/shared/src/main/scala/cats/effect/internals/Callback.scala, core/shared/src/main/scala/cats/effect/internals/MVarConcurrent.scala, core/shared/src/main/scala/cats/effect/package.scala, core/shared/src/test/scala/cats/effect/SyntaxTests.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala, laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala, laws/shared/src/test/scala/cats/effect/TestContextTests.scala, site/src/main/tut/datatypes/io.md, site/src/main/tut/typeclasses/concurrent-effect.md, site/src/main/tut/typeclasses/concurrent.md
This is a change proposal that breaks binary and source compatibility.
We can refrain from doing that and I'd like your opinion, but unfortunately we are breaking binary and source compatibility in the next release anyway, at least due to #278 and possibly #289.
NOTE this PR is needed as a precursor to the upcoming changes for fixing #267.
Changes:
1. demote `Concurrent#cancelable` from being a primitive operation by providing a default implementation; instances can override it
3. Make `cancelable` work with `F[Unit]` as the "cancel token" instead of `IO[Unit]`; thus we are making `Concurrent` independent of `IO`
4. Introduce a `type CancelToken[F[_]] = F[Unit]` alias to better document cancellation tokens used in the API, because working with `IO[IO[Unit]]` is damn confusing, versus …
=> Concurrent, version 2

build.sbt, core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala, core/shared/src/main/scala/cats/effect/Effect.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/SyncIO.scala, core/shared/src/test/scala/cats/effect/SyntaxTests.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/arbitrary.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestInstances.scala, laws/shared/src/test/scala/cats/effect/IOAsyncTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, laws/shared/src/test/scala/cats/effect/LTask.scala, laws/shared/src/test/scala/cats/effect/SyncIOTests.scala, site/src/main/tut/datatypes/io.md, site/src/main/tut/typeclasses/concurrent-effect.md, site/src/main/tut/typeclasses/effect.md
This is the polished version of #297.
Added the `SyncIO` type as a newtype over `IO`, exposing only synchronous constructors. This is an easy way to achieve parity with `IO` w.r.t. things like performance, stack safety, exception handling, etc. There's instances for `Sync[SyncIO]`, `Monoid[SyncIO[A]]` given `Monoid[A]`, `Semigroup[SyncIO[A]]` given `Semigroup[A]`, and `SemigroupK[SyncIO]`.
Signatures of `runAsync` and `runStepSync` on `Effect` and `runCancelable` on `ConcurrentEffect` were modified to return a `SyncIO` instead of an `IO`.
ScalaDoc and tests were lifted from IO and edited appropriately due to lack of cancelation support in IO. The duplication bothers me but users will be happier with the docs.
This is a joint PR between me and @dscleaver. I squashed everything in to one …
=> Added SyncIO data type for describing synchronous effectful computations

core/shared/src/main/scala/cats/effect/Clock.scala, core/shared/src/main/scala/cats/effect/ContextShift.scala, core/shared/src/main/scala/cats/effect/Timer.scala
In #289 we forgot to add an `@implicitNotFound` message for `ContextShift`.
Also modifies the message for `Clock` and `Timer` to be consistent.
=> Modify @implicitNotFound messages for Clock, ContextShift, Timer

site/src/main/tut/concurrency/basics.md, site/src/main/tut/concurrency/index.md
I've written something regarding Concurrency and I hope it could be good addition to documentation. :)
My idea is to gather all relevant information that is usually scattered around the internet, books and gitter conversations. With your review/contributions I believe it will become decent reference point for understanding basics of concurrency that are relevant to `Cats-Effect` and others.
As time passes and I understand more I'll try adding more information - I want to add short "Stack safety" section next but I scrapped it for now to do this PR and release anything. 
If you like this initiative we could make a TODO list and have corresponding issues to gradually make it more comprehensive.
It's probably the first time I'm writing something that long in English so I will really …
=> Add Concurrency Basics section

core/shared/src/main/scala/cats/effect/internals/IOBracket.scala, laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala
=> Fix #316: fix IO.bracket to be stack safe; add laws to SyncLaws

README.md
I had to dig around a little to find out how to do this and thought it might encourage PRs on improving the docs if this was stated explicitly somewhere.
=> Add instructions on building microsite to README

core/shared/src/main/scala/cats/effect/concurrent/Ref.scala
Fixes #320
I'm undecided about `getAndSet`, it still feels slightly like an implementation creep, and imho is quite useless given that it's just ~~`modify(old => old -> new)`~~ `modify(old => new -> old)`, but otoh it's not hard to implement like `lazySet` nor outright dangerous like `compareAndSet` so maybe it's fine to leave it there?
=> Remove compareAndSet and lazySet

core/shared/src/main/scala/cats/effect/IO.scala
I favor being explicit about what combinator I'm using. Also makes sense to have a named "smart constructor" for each IO constructor for consistency's sake. Historically, Monix `Task.apply` performed both a delay and inserted an asynchronous boundary, so was thrown off when I couldn't find a named `delay`.
=> Add delay combinator for IO

site/src/main/tut/concurrency/mvar.md
When I was reading the docs, I didn't understand how an MVar could be emptied, and the difference between `take` and `read` wasn't so clear (`read` is said to not modify, but `take` isn't explicitly said to empty the variable)
=> Note that MVar#take empties the variable

benchmarks/shared/src/main/scala/cats/effect/benchmarks/ECBenchmark.scala, core/js/src/main/scala/cats/effect/internals/IOAppCompanionPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOAppCompanionPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala, core/shared/src/main/scala/cats/effect/IOApp.scala
Introduces `IOApp.WithContext` on the JVM to support customization of the execution context and scheduler that underlie the implicit `ContextShift` and `Timer`. We await the termination of both to support a safe, customizable shutdown with pending tasks.
Benchmark shows no significant performance difference.
Fixes #337.  Based on @alexandru's gist of #337, and previous attempts at #339 and #341.
=> Add IOApp.WithContext for custom executors and schedulers

core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala
1. Make clear that these are scheduler threads
2. Give them a unique name, in the same spirit as the global execution context
=> Uniquely name cats-effect-scheduler threads

CODE_OF_CONDUCT.md, README.md
Changing the Code of Conduct from Typelevel to [Scala's Code of Conduct](https://www.scala-lang.org/conduct/), because this CoC is more standard and I think has a more positive phrasing. Scala's CoC has been [endorsed by Typelevel](https://typelevel.org/blog/2016/12/17/scala-coc.html).
Another reason I'm doing this change is that we need a list of project maintainers that can be responsible for moderation, because Cats-Effect is its own project with its own communication channels. But I don't want to impose this on anybody. So dear maintainers, feel free to add yourself to this list if you want to help 🙂
I did the [same change in Monix](https://github.com/monix/monix/pull/717).
=> Change to Scala`s Code of Conduct

README.md
As of version [0.25](https://github.com/finagle/finch/releases/tag/v0.25.0), Finch leverages cats-effect to abstract over concrete effect implementations.
=> Add Finch to Libraries that depend on cats-effect

.travis.yml
Hello guys!
In my other pull request I saw that the build is failing due to oracle java 10 being deprecated https://travis-ci.org/typelevel/cats-effect/jobs/444783719 . Since w have java 11 ready and released I decided that it is wise to change java 10 to java 11 in build.
=> Updated oraclejdk10 to openjdk11 in travis configuration

core/shared/src/main/scala/cats/effect/ContextShift.scala
Just for convenience, so that something like `ContextShift[F].shift *> someOp()` is possible
=> apply was added to ContextShift

core/shared/src/main/scala/cats/effect/Timer.scala
This PR brings back the summoner `apply` for Timer.
I think the decision of removing the default instance for Timer is solid, since you can't guarantee coherence (and you see it as soon as you try using `TextContext`).
I also think that the strategy of proving an instance via `IOApp` is solid, since it links `Timer` to an "environment", and it fits well with a general strategy for final tagless algebras that I like to call `implicit call sites`.
However, removing `apply` went a step too far, and I don't think it brings anything to the table apart from inconvenience, especially considering that `Timer` is being passed implicitly anyway in most of the ecosystem.
=> Add summoner for Timer

build.sbt, core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala, core/shared/src/test/scala/cats/effect/concurrent/SemaphoreTests.scala
Addresses a leak in `withPermit` discussed in #382. Also addresses a leak of permits when `acquire(N)` is cancelled after receiving some but not all of its permits.
=> Fixed resource leak in Semaphore#withPermit and acquire(N)

core/shared/src/main/scala/cats/effect/ContextShift.scala
`f` was renamed to `fa` in e8301908d7628d572ba37d44cfa6cd2dcf43c584 but not in the first Scaladoc paragraph.
=> Update reference to evalOn's fa parameter

core/shared/src/main/scala/cats/effect/ContextShift.scala, laws/shared/src/test/scala/cats/effect/ContextShiftTests.scala
This adds a variant of `evalOn` that returns a natural transformation.
Can make it easier to "extend" a natural transformation like Doobie's interpreter:
```scala
implicit val F: ContextShift[F] = ...
type G[A] = Kleisli[F, Connection, A]
transactor.copy(interpret0 =
transactor.interpret.andThen(λ[G ~> G](_.mapK(F.evalOn(blockingContext)))))
```
(would look even better if there was a FunctionK-returning equivalent of `Kleisli#mapK` (https://github.com/typelevel/cats/pull/2450), but it's a step forward)
I can follow up with some tests if needed (and if the feature is wanted), so feel free to let me know what you think.
=> Add ContextShift#evalOnK

site/src/main/resources/microsite/data/menu.yml, site/src/main/tut/tutorial/tutorial.md
Tutorial with a learn-by-doing approach, showcasing how to use main cats-effect types. Two main parts: first building a program to copy files, second building a TCP server.
- Tutorial, as it'd be seen in cats-effect page, can be read at https://lrodero.github.io/cats-effect/tutorial/tutorial.html
- Source code of the tutorial examples is available at https://github.com/lrodero/cats-effect-tutorial (I'd happy to contribute that code as well to cats-effect, but I don't know if that would introduce too much noise)
=> Tutorial for cats-effect

core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala, core/shared/src/main/scala/cats/effect/concurrent/MVar.scala, core/shared/src/main/scala/cats/effect/concurrent/Ref.scala, core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
Add dual effect constructors, using another `Sync` instance for delay state creation as discussed in #373
=> dual effect concurrent data constructors

.travis.yml, build.sbt
closes #66 
I've got a few warnings when compiling with `scala-2.13.0-M5`. Most of them related to `Either` being now right-biased. Not sure whether it should be treated differently or not.
```
[info] Compiling 61 Scala sources to /workspace/oss/cats-effect/core/js/target/scala-2.13.0-M5/classes ...
[info]   Compilation completed in 10.16s.
[warn] /workspace/oss/cats-effect/core/shared/src/main/scala/cats/effect/syntax/BracketSyntax.scala:24:71: parameter value bracket in method catsEffectSyntaxBracket is never used
[warn]   implicit def catsEffectSyntaxBracket[F[_], A, E](fa: F[A])(implicit bracket: Bracket[F, E]): BracketOps[F, E, A] =
[warn]                                                                       ^
[warn] /workspace/oss/cats-effect/core/shared/src/main/scala/cats/effect/sy …
```
=> Upgrade to Scala 2.12.7 and 2.13.0-M5

core/shared/src/main/scala/cats/effect/Resource.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala
This enables it to be found by IDEs which have issues with partial
unification and feels like it should be there since the class already
provides `flatMap`.
=> Add a `map` method directly onto `Resource`

site/src/main/tut/datatypes/io.md
Since there is no longer implicit context shift carried with global
execution context I removed this part of docs. I added a quick example
how to setup context shift using method from IO. This was the part I was
missing when reading the documentation. This fixes #404
=> Remove misleading information about Context shift from IO parallel tutorial

site/src/main/tut/datatypes/io.md
fixes following error in [cats-effect parallemsim example](https://typelevel.org/cats-effect/datatypes/io.html#parmapn) after adding `implcit ContextShift[IO]`
```scala
could not find implicit value for parameter p: cats.NonEmptyParallel[cats.effect.IO,F]
```
as the definition for `parMapN` is looking for `NonEmptyParallel`
```scala
def parMapN[F[_], Z](f: (A0, A1, A2) => Z)(implicit p: NonEmptyParallel[M, F]): M[Z] = Parallel.parMap3(t3._1, t3._2, t3._3)(f)
```
=> documentation - add one contextShift example out of three provided options

core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala
Imho `sequence` will not catch bugs related to concurrent modifications, but `parSequence` will do.
=> Use parSequence rather than sequence in RefTests

.travis.yml, build.sbt, site/src/main/tut/datatypes/io.md, site/src/main/tut/datatypes/resource.md, site/src/main/tut/typeclasses/sync.md
This started out as me just attempting to provide a link to the
"Acquiring and releasing `Resource`s" section of the tutorial from with
tin the `Resource` data type doc. But then I went down a bit of a rabbit
hole...
There was a Scala 2.12.6 vs 2.12.7 mismatch between `build.sbt` and
`.travis.yml`. This meant that the build hasn't actually been compiling
the docs recently. So I fixed a few spots that weren't compiling in the
docs (though I'm not sure whether I fixed them in the preferred way). I
went ahead and attempted to make the scala version check for the docs
build a bit more lenient to hopefully avoid a similar issue in the
future. Admittedly my bash skills are lacking, so we should probably
check that it works as expected in the Travis build.
=> Do some doc fixing

build.sbt, laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala
I thought it would be reasonable to check that.
It's easy to break this law, for example by removing the `suspend` call here: https://github.com/kubukoz/slick-effect/blob/3af6c4ab8950f42ebbcaaed0fc5621c503bb258a/src/main/scala/slickeffect/DBIOAsync.scala#L27. That would memoize the promise, and it would only be completed once.
=> Add "repeated asyncF evaluation not memoized" law

core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala
Really tiny pedantic PR!
`cats.effect.fusionMaxStackDepth` is a system property not an environment variable
See:
* https://docs.oracle.com/javase/tutorial/essential/environment/properties.html
* https://en.wikipedia.org/wiki/Environment_variable
=> Documentation fusionMaxStackDepth system property referred to as env var

core/shared/src/main/scala/cats/effect/Resource.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala
* Implement it by recursing over the structure to apply the transform
* This may not be stack-safe, but it's no less stack safe than `use` so I can't tell
=> add `mapK` onto `Resource`

site/src/main/tut/datatypes/io.md
fib should calculate (0), 1, 1, 2, ... starting from n = 0. Was: 1, 2…
=> Fix fib in cats-effect/datatypes documentation.

site/src/main/tut/concurrency/semaphore.md
Remove unnecessary instance of `Parallel[IO, IO]` from Semaphore documentation as ` Parallel[IO, IO.Par]` works just fine there.
=> Remove unnecessary Parallel instance in semaphore docs.

core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
This adds `fromTry` to the `IO` companion object. It is available on the `ApplicativeError[IO, Throwable]` instance, but this can be a bit tedious to type every time you want to use it (and is non-obvious to folks who are new to FP).
=> Add IO.fromTry

site/src/main/tut/tutorial/tutorial.md
Hi, I'm new to Cats Effect, and tried the tutorial. This document is great, but I was a bit confused why the conventional `apply[F[_]]` isn't used to obtain implicit `ContextShift[F]` in the codes. I found that there wasn't the `apply[F[_]]` method for `ContextShift` at version 1.0.0, but we have it now (v1.2.0). It would be more readable if we use `apply[F[_]]` to obtain implicit value!
=> Use ContextShift.apply in the tutorial

core/shared/src/main/scala/cats/effect/Resource.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala
Currently `liftF` on `Resource` is implemented as an `Allocated` node with a no-op release, so 
`Resource.liftF(fa)` produces `Resource.Allocated(fa, _ => F.unit)`. 
During interpretation, `Allocated` nodes get translated into `bracket` calls, so `liftF` ends up producing `bracket(fa)(...)(_ => F.unit)`, which is no longer a no-op because `fa` is made uninterruptible by the fact that it's being passed as a `bracket.acquire` action.
----------
As a consequence, the following law is broken:
```
Resource.liftF(fa).use(IO.pure) <-> fa
```
and what ends up holding is
```
Resource.liftF(fa).use(IO.pure) <-> fa.uncancelable
```
(This wasn't caught by our existing property tests for this law)
----------
On a practical level, this caused a bug in fs2 where compiling a Stream down to a  Resource …
=> Make Resource.liftF interruptible

.travis.yml
https://api.travis-ci.org/v3/job/476841108/log.txt
```
/home/travis/.travis/job_stages: line 104: [: missing `]'
travis_time:end:01382cf6:start=1546954447220165630,finish=1546954447223387832,duration=3222202
[0K[32;1mThe command "if [ "$TRAVIS_SCALA_VERSION" = "2.12.7"]; then
sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite
fi
" exited with 0.[0m
```
`makeMicrosite` is silently not running.  This is responsible for not detecting the errors mentioned in #460.
=> Fix shell test to makeMicrosite

.travis.yml
[openjdk11 builds are broken](https://travis-ci.community/t/install-of-openjdk11-is-failing-again/3061) again on trusty. xenial has it preinstalled, and [trusty is EOL](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) on April 30. Let's switch now.
More breaking news: oraclejdk8 doesn't install on xenial, so let's try openjdk8.
=> Switch to xenial and openjdk8

.travis.yml, build.sbt, core/js/src/test/scala/cats/effect/internals/Platform.scala, core/jvm/src/test/scala/cats/effect/internals/Platform.scala, core/shared/src/test/scala/cats/effect/IOAppTests.scala, core/shared/src/test/scala/cats/effect/concurrent/DeferredTests.scala, core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala, core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala, core/shared/src/test/scala/cats/effect/concurrent/SemaphoreTests.scala, core/shared/src/test/scala/cats/effect/internals/ArrayStackTests.scala, core/shared/src/test/scala/cats/effect/internals/CallbackTests.scala, core/shared/src/test/scala/cats/effect/internals/CancelUtilsTests.scala, core/shared/src/test/scala/cats/effect/internals/ForwardCancelableTests.scala, core/shared/src/test/scala/cats/effect/internals/IOConnectionTests.scala, core/shared/src/test/scala/cats/effect/internals/LinkedMapTests.scala, core/shared/src/test/scala/cats/effect/internals/TrampolineECTests.scala, laws/js/src/test/scala/cats/effect/IOJSTests.scala, laws/jvm/src/test/scala/cats/effect/DeferredJVMTests.scala, laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala, laws/jvm/src/test/scala/cats/effect/MVarJVMTests.scala, laws/jvm/src/test/scala/cats/effect/SemaphoreJVMTests.scala, laws/shared/src/test/scala/cats/effect/BaseTestsSuite.scala, laws/shared/src/test/scala/cats/effect/IOAsyncTests.scala, laws/shared/src/test/scala/cats/effect/TimerTests.scala
Fixes #507.  Blocked by https://github.com/typelevel/cats/pull/2783.
=> Scala 2.13.0-RC1 support

core/js/src/main/scala/cats/effect/internals/ResourcePlatform.scala, core/jvm/src/main/scala/cats/effect/internals/ResourcePlatform.scala, core/shared/src/main/scala/cats/effect/Resource.scala, laws/jvm/src/test/scala/cats/effect/ResourceJVMTests.scala
This works exactly like `Resource.fromAutoClosable`, but for another standard interface. I had to add a `ResourcePlatform`, since this interface is not present in JS.
=> Add Resource.fromDestroyable

site/src/main/tut/concurrency/mvar.md
Remove reference to tryRead in docs on MVar, as it doesn't actually exist
=> Remove reference to tryRead in docs on MVar

build.sbt, laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/EffectTests.scala
As long as we're breaking binary compatibility in laws, we can eliminate two warnings with this.
=> Remove unused Eq[IO[Either[F[A], A]]] from EffectTests

site/src/main/tut/tutorial/tutorial.md
There is a catch on current tutorial code: the TCP server tries to `.cancel` a fiber that is based on `bracketCase`. Since CE 1.1.0 this cancellation will block the caller until the bracket finalizes, however the TCP server needs that cancellation to return immediately. As the tutorial is based on 1.0.0, it needs to be updated.
This patch modifies the tutorial code as needed by running the cancellation in its own fiber (`.cancel.start`), following a suggestion from Alex Nedelcu in gitter. It also introduces some text explaining why we need to do that. Finally it includes an unrelated typo fix.
The final result can be seen at https://lrodero.github.io/cats-effect/tutorial/tutorial.html
=> Patch for tutorial, to prevent blocking in cancellation

core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
Apparently MiMa claims this is binary incompatible, but maybe it's a false positive (the trait is `private[effect]` so maybe it only matters for implementations), so I submitted it anyway.
Please let me know what you think about making IO.Par's applicative commutative (I checked it before and it passed the laws... apparently)
=> Make IO.Par's applicative commutative

core/shared/src/main/scala/cats/effect/Resource.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala
A cross between `flatTap` and `evalMap`. Use case - an action returning a temporary resource with custom setup. For me this pattern pops up all the time when writing logic that uses temporary files (create a temporary file, write some data to it, yield the file).
=> Add Resource.evalTap

build.sbt
When the tests are run here 0.11.1 is evicted and 0.11.2-M1 is used (which is why they're working), but for cats-effect-laws users with a configuration like this:
```scala
scalaVersion := "2.12.8"
libraryDependencies ++= Seq(
"org.scalatest" %% "scalatest" % "3.1.0-SNAP9",
"org.typelevel" %% "cats-effect-laws" % "2.0.0-M1",
"org.typelevel" %% "discipline" % "0.11.2-M1",
"org.scalatestplus" %% "scalatestplus-scalacheck" % "1.0.0-SNAP4"
)
```
…the eviction goes the wrong way:
```
[info] Here are other dependency conflicts that were resolved:
[info]  * org.typelevel:discipline_2.12:0.11.1 is selected over 0.11.2-M1
[info]      +- org.typelevel:cats-effect-laws_2.12:2.0.0-M1       (depends on 0.11.1)
[info]      +- org.typelevel:cats-laws_2.12:2.0.0-M1 ()           (depends on 0.11.2-M1) …
```
=> Update Discipline version

CODE_OF_CONDUCT.md, README.md
Nothing substantial:
1. The link is broken on the website, so make it absolute.  Thanks to @etorreborre for the report.
2. Link to the Typelevel copy so we're not burdening Scala's moderators if people click through.
=> Code of Conduct tweaks

core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
After a chat on [Gitter conversation](https://gitter.im/typelevel/cats-effect?at=5cdebc5f6366992a94d3e51c) a PR to fix the following issue.
```scala
import cats.effects.IO
IO.pure(1).uncancelable.unsafeRunSync()
// Exception in thread "main" java.lang.AssertionError: unreachable
//  at cats.effect.IO.unsafeRunTimed(IO.scala:328)
//  at cats.effect.IO.unsafeRunSync(IO.scala:240)
```
This is caused because the callstack is still empty at that point in `IORunLoop#step` and as an optimization the `currentIO` doesn't get wrapped in `Async`.
This causes `unsafeRunTimed` to run into `case _ => throw AssertionError("unreachable")`
=> IORunLoop#step bug

laws/shared/src/test/scala/cats/effect/TimerTests.scala
This avoids granularity issues in system time as uncovered by @rossabaker in #540
=> Increased all the sleeps in Timer tests by an order of magnitude

core/js/src/main/scala/cats/effect/internals/IOAppPlatform.scala
Without this, a signaled app exits successfully instead of with the expected exit code.
=> Backport Scala.js IOApp signal handler fix from #540

build.sbt, core/shared/src/main/scala/cats/effect/Bracket.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/syntax/BracketSyntax.scala, laws/shared/src/main/scala/cats/effect/laws/BracketLaws.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/BracketTests.scala, laws/shared/src/test/scala/cats/effect/ConcurrentContinualTests.scala
This PR adds `onCancel` to execute an action on cancelation, and `continual`, an interruption safe equivalent of `attempt.flatMap`.
Although there is a longer discussion to be had wrt our cancelation model, in this PR I focused exclusively on implementing things in combinator land, with no internal changes: these should be usable today, by any effect. The main drawback right now is the heaviness of `continual`.
~~MiMa tells me this is fully binary compatible.~~ ( -.-" )
Breaks bincompat on 2.11 only
=> onCancel + continual

build.sbt, core/shared/src/main/scala/cats/effect/IO.scala, laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala, laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
This is probably the most serious bit of compatibility breakage we're going to introduce in 2.0, since it can actually break source compatibility by forcing people to thread a `ContextShift[IO]` where one was not previously necessary. With that said, any cases where people *weren't* already `shift`ing following a `fromFuture` were probably bugs, so I'm more or less okay with that.
I hate the fact that I had to use `IOFromFuture` in the laws, but I'm not sure it's fundamentally worse than the fact that we were already using `IO` in the laws. I filed #545 to track that, as it will need to be excised in 3.0.
Fixes #444
=> Enforce shifting within IO.fromFuture

core/shared/src/main/scala/cats/effect/IO.scala
=> Shift on errors in IO.fromFuture

core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala, core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala, core/shared/src/main/scala/cats/effect/internals/IOContextShift.scala
This pulls `IOApp` off the global `ExecutionContext` and onto a custom one that has better properties. Specifically:
- Crashes on truly fatal errors (rather than doing something horrible, like swallowing `OutOfMemoryError`)
- Lower-bounds the pool to 2 threads (global can go down to 1 if you only have 1 core). Having a 1-thread pool can cause deadlocks in poorly written code. Poorly written code is poor, but I'd rather not give them more headaches, and it's enough of an edge case that I'm okay with it.
- Avoids issues with global pool pollution by third-party code
- Avoids fork f***ing join, which is horrible for this kind of stuff
Related to #347. I'd like to hear from @rossabaker (and ideally @alexandru) as to their thoughts on the design tradeoffs here, and whether I should expand the …
=> Replaced global ContextShift/Timer instances on JVM

site/src/main/tut/concurrency/basics.md
In the hindsight I think it was confusing and/or false
=> Remove logical/native threads distinction from Concurrency Basics doc

.gitignore, core/js/src/main/scala/cats/effect/internals/BlockerPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/BlockerPlatform.scala, core/shared/src/main/scala/cats/effect/Blocker.scala, core/shared/src/main/scala/cats/effect/ContextShift.scala, site/src/main/tut/datatypes/contextshift.md
=> Added Blocker, a new type for blocking execution contexts

build.sbt, core/shared/src/main/scala/cats/effect/IO.scala
Brings back `fromFuture` in the old shape, but deprecated (only for documentation reasons, since the method can't legally be called anyway) and package-private.
Hopefully this can end up in 2.0.0.
=> Restore binary compat in core on 2.12

core/shared/src/main/scala/cats/effect/IO.scala
=> align scaladoc with examples from the official docs for IO.shift - fixes #559

core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala
Should prevent leaking timeouts.
=> Make default scheduler remove cancelled tasks.

site/src/main/tut/datatypes/clock.md, site/src/main/tut/datatypes/contextshift.md, site/src/main/tut/datatypes/io.md, site/src/main/tut/typeclasses/async.md
It took me a longer while to realise what `N.B.` means in the docs. IMO `important` is more readable and expresses the intent in a cleaner way
=> Get rid of N.B. in documentation

core/shared/src/main/scala/cats/effect/Fiber.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala, laws/shared/src/test/scala/cats/effect/BaseTestsSuite.scala, laws/shared/src/test/scala/cats/effect/FiberTests.scala
See issue #405 
This instance implements the notion of `|+|` as a parallel race between two of its sides. Whoever returns successfully (ie. without error) first wins. `empty` is chosen to be `raiseError(Empty)` where `Empty` is an unique exception subclass defined in the `Fiber` companion. This decision, IMO, prevents some issues that arise if `empty` was to be defined as `never`. First, it preserves absorption laws ie `ff <*> empty <-> empty` . Second, it preserves monoid identity laws ie. `<fail> |+| empty <-> <fail>` and `empty |+| <fail> <-> <fail>` (in case of `never`, `empty` consumes the failing computation).
To test the respective laws, I needed to change how `TestContext` behaves. Unfortunately, in the presence of both non-deterministic _combine_ and semiringal `Alternative` …
=> Add an Alternative instance for Fiber

project/plugins.sbt, site/src/main/tut/datatypes/io.md
Resolves the error in https://github.com/typelevel/cats-effect/pull/570, which is caused by trailing comments in tut sheds as described [here](https://github.com/tpolecat/tut/issues/243#issuecomment-438288206). Adding a trailing `()` fixes it, though it looks slightly odd.
=> sbt microsites 0.7.27

.gitignore, core/js/src/main/scala/cats/effect/internals/BlockerPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/BlockerPlatform.scala, core/shared/src/main/scala/cats/effect/Async.scala, core/shared/src/main/scala/cats/effect/Blocker.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/ContextShift.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/Resource.scala, core/shared/src/main/scala/cats/effect/concurrent/Ref.scala, core/shared/src/main/scala/cats/effect/syntax/ConcurrentSyntax.scala, core/shared/src/test/scala/cats/effect/AsyncTests.scala, core/shared/src/test/scala/cats/effect/ConcurrentTests.scala, core/shared/src/test/scala/cats/effect/SyntaxTests.scala, laws/shared/src/test/scala/cats/effect/RefTests.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala, site/src/main/tut/datatypes/contextshift.md
* #554
* #556: Omits ContextShift#blockOn for binary compatibility
* #498: Omits syntax for binary compatibility
* #560
* #567
* #574
* #586
* #591
Should be released as version 1.4.0 for semantic versioning.
=> 1.4.0: omnibus bug fix, feature, and scaladoc backport

core/shared/src/main/scala/cats/effect/Fiber.scala, core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala, laws/shared/src/test/scala/cats/effect/BaseTestsSuite.scala, laws/shared/src/test/scala/cats/effect/FiberTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
The instances were unlawful as specified. It's possible for us to fix this by doing the following:
- Create a structure much like `Coyoneda` within `Fiber`
- Define an explicit representation of a *canceled* `Fiber` (needed for `empty`)
The latter is the tricky one, since we have no direct ways of representing this right now due to `join`'s extremely restricted type (this causes other problems, too). The former is also slightly annoying. For posterity, there are two options on the former:
- Embed it within a custom `Fiber` subtype within the `Alternative` instance, exposed only to that `Alternative` instance. This has the advantage of keeping mainline `Fiber` quite clean, but the disadvantage of requiring a typecase in each combinator to re-specialize the `Fiber` type. This also implies …
=> Revert MonoidK for IO.Par and Alternative for Fiber

site/src/main/tut/concurrency/mvar.md
I think a coworker of mine found a bug in one of the `MVar` examples. https://typelevel.org/cats-effect/concurrency/mvar.html#use-case-asynchronous-lock-binary-semaphore-mutex
When you make a new `MLock`, it isn't initialized, so if you call `acquire` you will just be waiting forever. It basically starts in an already pre-acquired state which might be confusing. I replaced the `MVar[IO].empty[Unit]` call with a call to `MVar[IO].of(())` which should work.
=> (Docs) Fix MLock constructor to not hang on first call to 'acquire'

core/shared/src/main/scala/cats/effect/Timer.scala
* It's consistent with our other links
* It's consistent with what we build against
* It's not EOL
* I've already said too much about this one-bit diff
=> Link to Java 8 javadoc instead of EOL Java 9

core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala, core/jvm/src/test/scala/cats/effect/internals/JvmIOTimerTests.scala, site/src/main/tut/datatypes/timer.md
Global configuration through mutable system properties is a wart, but so are sbt sessions that run out of memory.  We'll aim higher in Cats-Effect 3.
Fixes #347.
=> Configure the global scheduler with system properties

build.sbt
We want our laws to be usable from Scalatest, but not prescribe a specific version of Scalatest.  This makes cats-laws depend only on discipline-core.  No code changes are necessary.
=> Laws depend only on discipline-core

core/jvm/src/main/scala/cats/effect/internals/BlockerPlatform.scala, core/jvm/src/main/scala/cats/effect/internals/IOAppCompanionPlatform.scala, core/shared/src/main/scala/cats/effect/Blocker.scala, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
This PR fixes typo and invalid closing backticks in the documentation
=> Fix invalid references in the documentation

.scalafmt.conf, core/shared/src/main/scala/cats/effect/Sync.scala, core/shared/src/main/scala/cats/effect/internals/IOForkedStart.scala
Scalafmt 2.1.1 inserts a new line after else word. https://github.com/scalameta/scalafmt/issues/1509
Scala-steward PR: https://github.com/typelevel/cats-effect/pull/669
This PR fixes scalafmt checks.
=> Update scalafmt-core to 2.1.1

site/src/main/mdoc/datatypes/io.md
`Pretty much we have been using some "unsafe" operations in the previous example` -> `We have been using some "unsafe" operations pretty much everywhere in the previous examples`
=> Fix incorrect phrase in "Unsafe" Operations part

core/shared/src/main/scala/cats/effect/Clock.scala, core/shared/src/main/scala/cats/effect/Timer.scala, laws/shared/src/test/scala/cats/effect/TimerTests.scala
Ref https://github.com/typelevel/cats-effect/issues/696
=> Issue 696: Add a derivation for Timer[Resource[F, ?]] whenever Timer[F] is in scope

core/shared/src/main/scala/cats/effect/Blocker.scala
This adds a `ContextShift.evalOnK` alternative for `Blocker`.  Unlike `evalOnK`, we can put this directly on the `Blocker` where it makes the most sense.
=> Add Blocker.blockOnK

.travis.yml, README.md, build.sbt, core/shared/src/main/scala/cats/effect/package.scala, versioning.md
=> Drop Scala 2.11.x

core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/syntax/ConcurrentSyntax.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
This includes several commits from #639 which will be properly cleaned up once the other PR is closed.
I'm not too attached to the name, but it carries a nice meaning that I believe will be friendly to users.
Closes #628
=> `start` as Resource - `background`

build.sbt, core/shared/src/main/scala/cats/effect/Concurrent.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/syntax/ConcurrentSyntax.scala
Follow-up to #640, since #713 has been merged.
=> Move `background` to Concurrent the trait, remove 2.11 leftovers

.gitignore, .travis.yml, site/Gemfile, site/Gemfile.lock
Notes:
- instead of doing `gem install jekyll`, we're switching to usage of [bundler](https://bundler.io/) for managing our Ruby dependencies via a [Gemfile](https://bundler.io/gemfile.html)
- `gem update --system` is totally not needed, not sure why it was even there, of course it creates conflicts
- we can use a "gem set"  (e.g. `@cats-effect`, which sets a specific GEM_HOME where system dependencies get installed) if we need to reinstall all dependencies from scratch (in this context I don't think it's needed, but it's nice to have it there as a comment, in case of future conflicts)
=> Microsite: use bundler for installing Jekyll & Ruby deps

.scalafmt.conf, core/shared/src/main/scala/cats/effect/internals/IOBracket.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
If `IO` is canceled during `acquire` in bracket, `use` is still evaluated. 
If `use` is cancelable then it will be canceled so to me it looks like an oversight.
Before the change:
`IO(println("A")) >> IO.cancelBoundary >> IO(println("B"))` will print "A"
`IO(println("A")) >> IO(println("B"))` will print "A" and then "B" unless it is canceled on flatmap.
After the change nothing should be printed at all.
See the gitter question: https://gitter.im/typelevel/cats-effect?at=5ddbe546f3ea522f26667d78
```scala
def acquire: IO[String] = {
IO(logger.info("Resource acquiring...")) >> timer.sleep(5.seconds) >> IO {
logger.info("Resource acquired")
"some resource"
}
}
def release(resource: String): IO[Unit] = {
IO(logger.info(s"Releasing $resource"))
}
val action = acquire.bracket { r => …
```
=> Bracket: Do not evaluate "use" if "acquire" is canceled

playground.scala, src/main/scala/ce3/concurrent.scala
=> [naming things] CE3: Rename `yielding` to `cede`

.travis.yml, build.sbt, core/shared/src/main/scala/cats/effect/Resource.scala
Following the discussion in #617 this simply makes Resource covariant. Binary compatibility is not affected as non-generic parts of the method signatures are unchanged.
=> Fix #617: Make Resource covariant in F and A

README.md
Hi, I updated to the latest URL(https://console4cats.profunktor.dev/) from URL(https://gvolpe.github.io/console4cats/).
=> Update console4cats url

.travis.yml, site/src/main/mdoc/datatypes/io.md
Hi, I wish to update the docs to reflect the current implementation, but I am not sure how much implementation details to expose?
Another question: I notice the microsite does not work out of the box locally as the microsite project uses a non-default `baseUrl`, is this something we expect?
=> Update docs about cancellation to reflect latest implementation

core/shared/src/main/scala/cats/effect/internals/IOBracket.scala, core/shared/src/main/scala/cats/effect/internals/IOConnection.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala
Fixes #721
Not 100% sure about the test, I'm counting on final suggestions from @djspiewak and @kubukoz and we could include it in the laws as well
The problem was happening when `release` has been already called by other action
=> Cancel should always wait for the finalizer

build.sbt, laws/shared/src/test/scala/cats/effect/BaseTestsSuite.scala
This release requires manual update 
Release notes: https://github.com/typelevel/discipline-scalatest/releases/tag/v1.0.0-RC3
=> Update discipline-scalatest to 1.0.0-RC3

core/shared/src/main/scala/cats/effect/internals/ArrayStack.scala, core/shared/src/test/scala/cats/effect/internals/ArrayStackTests.scala
The internal `ArrayStack` here differs from the standard library's in that `pop()` returns `null` for the empty stack, but this is only possible for primitive types because of this extremely weird behavior in Scala 2 (which is fixed in Dotty):
```scala
scala> def foo[A]: A = null.asInstanceOf[A]
def foo[A] => A
scala> foo[Int]
val res0: Int = 0
scala> foo[Int].asInstanceOf[AnyRef]                   
val res1: AnyRef = null
```
As @smarter says:
> there's no universe where having `foo[Int].asInstanceOf[AnyRef]` return something different from `val x = foo[Int]; x.asInstanceOf[AnyRef]` makes sense
`ArrayStack` isn't currently used with primitive types anywhere outside its tests, and it's not part of the public Scala API, so I think it makes sense just to restrict it to `AnyRef` and adjust …
=> Restrict ArrayStack to AnyRef

core/shared/src/main/scala/cats/effect/Bracket.scala, core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/SyncEffect.scala, core/shared/src/main/scala/cats/effect/concurrent/Ref.scala, core/shared/src/main/scala/cats/effect/internals/IOBracket.scala, core/shared/src/main/scala/cats/effect/internals/IOConnection.scala, core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala, core/shared/src/main/scala/cats/effect/internals/IOStart.scala, core/shared/src/test/scala/cats/effect/AsyncTests.scala, core/shared/src/test/scala/cats/effect/ConcurrentTests.scala, core/shared/src/test/scala/cats/effect/IOAppTests.scala, core/shared/src/test/scala/cats/effect/SyntaxTests.scala, core/shared/src/test/scala/cats/effect/concurrent/DeferredTests.scala, core/shared/src/test/scala/cats/effect/concurrent/ExitCodeTests.scala, core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala, core/shared/src/test/scala/cats/effect/concurrent/SemaphoreTests.scala, laws/shared/src/test/scala/cats/effect/FiberTests.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala
This is a set of changes that prepare for Dotty cross-building but are reasonable to do now:
* I've replaced kind-projector's `?` with `*`, [which will be supported in Dotty soon](https://github.com/lampepfl/dotty/pull/7775).
* Dotty is pickier about parentheses (which also helps readability and consistency in my view).
* Dotty doesn't support eta-expansion syntax for converting by-name parameters to `Function0`.
* Dotty warns on `final` on case objects, and it doesn't do anything on Scala 2.
* Dotty doesn't have `do-while`, and recommends the rewrite I've done here.
* In a few places we rely on Scala 2 value discarding, which I've changed to either `.void` or `; ()`.
* One test extends `BeforeAndAfterAll` but doesn't use any of its methods, and it was causing problems with my local Dotty …
=> Some small changes for Dotty compatibility

laws/js/src/test/scala/cats/effect/internals/IOContextShiftTests.scala, laws/jvm/src/test/scala/cats/effect/DeferredJVMTests.scala, laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala, laws/jvm/src/test/scala/cats/effect/MVarJVMTests.scala, laws/jvm/src/test/scala/cats/effect/SemaphoreJVMTests.scala, laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala, laws/shared/src/test/scala/cats/effect/ConcurrentCancelableFTests.scala, laws/shared/src/test/scala/cats/effect/ConcurrentContinualTests.scala, laws/shared/src/test/scala/cats/effect/ContextShiftTests.scala, laws/shared/src/test/scala/cats/effect/FiberTests.scala, laws/shared/src/test/scala/cats/effect/IOAsyncTests.scala, laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala, laws/shared/src/test/scala/cats/effect/IOTests.scala, laws/shared/src/test/scala/cats/effect/InstancesTests.scala, laws/shared/src/test/scala/cats/effect/MemoizeTests.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala, laws/shared/src/test/scala/cats/effect/SyncIOTests.scala, laws/shared/src/test/scala/cats/effect/TestContextTests.scala
This is a follow-up to #757 for the laws module. The biggest part of the change is due to the tests relying on the fact that Scala 2 won't consider an implicit value in implicit search in its own definition if it doesn't have a type annotation. So for example this appears dozens of times:
```scala
implicit val cs = ec.contextShift[IO]
```
The `contextShift` method takes an `Async[IO]`, and there are a couple of implicit methods on `IO` that can provide this: `ioConcurrentEffect`, the higher-priority instance that's available when there's a `ContextShift` instance in scope for `IO`, and `ioEffect`, a lower-priority instances with no constraints.
When `cs` has no type annotation, `ioEffect` is chosen, since in effect the compiler doesn't yet know it's defining an implicit `ContextShift[IO]` …
=> Dotty-friendly changes for the laws module

build.sbt
Sets `permalink` property for root index page.
The new default use of `mdoc` in `sbt-microsites` led to some slight changes when using extra `.md` files. This change lets the site to serve again the root page correctly.
=> [Website docs] Fix home page path

site/src/main/mdoc/concurrency/index.md
Not sure if it's the proper way to fix things, but they are leading to a non-existent page with `.md` suffix and works with `html` suffix here: https://typelevel.org/cats-effect/concurrency/
=> Fix Concurrency links to other pages

core/shared/src/main/scala/cats/effect/Resource.scala, laws/shared/src/test/scala/cats/effect/ResourceTests.scala, site/src/main/mdoc/datatypes/resource.md
Yesterday @mpilquist suggested in the gitter channel that most classes that implement `AutoClosable` are blocking in its construction and `close`. As such, those operations should be called using a **Blocker**. Thus, this makes `Resource.fromAutoClosable` conceptually _"broken"_.
This PR attempts to solve that problem.
I have a couple of questions:
+ Do you all agree that this should be the expected behavior or not?
+ ~I believe not all `AutoClosable` are blocking, should we ignore that minority just for sake of consistency? or maybe we should leave both alternatives?~
+ ~Assuming we decide to get rid of the old method, what should we do with it? It has to be preserved for binary compatibility, but it shouldn't be exposed for use anymore. I think we could deprecate it. However, @kubukoz …
=> Using blocker in Resorce.fromAutoClosable

README.md, build.sbt, site/Gemfile, site/Gemfile.lock, site/src/main/mdoc/concurrency/index.md, site/src/main/mdoc/concurrency/mvar.md, site/src/main/mdoc/datatypes/index.md, site/src/main/mdoc/datatypes/io.md, site/src/main/mdoc/datatypes/syncio.md
Motivation:
- Links to the relative markdown pages stopped working.
Modification:
- Add jekyll plugin to support relative links.
- Modify links to ".html" to ".md" to keep warning when file doesn't exist such as
```
warning: datatypes/index.md:12:5: Unknown link 'datatypes/io2.md', did you mean 'datatypes/io.md'?
^^^^^^^^^^^^
```
It wouldn't happen if you point to an html.
Result:
- Relative links started to work and warnings are in place.
=> Docs: fix broken links; fixes #772

core/shared/src/main/scala/cats/effect/concurrent/Ref.scala, core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala
Leaving `setAndGet(a: A): F[A]` out because it's useless (the parameter you pass is the return value).
=> Add getAndUpdate, updateAndGet to Ref

core/shared/src/main/scala/cats/effect/IO.scala, laws/shared/src/main/scala/cats/effect/laws/discipline/arbitrary.scala, site/src/main/mdoc/concurrency/basics.md, site/src/main/mdoc/datatypes/fiber.md, site/src/main/mdoc/datatypes/io.md, site/src/main/mdoc/datatypes/ioapp.md, site/src/main/mdoc/datatypes/resource.md, site/src/main/mdoc/datatypes/timer.md
One of the factors in attracting new users is discoverability. I think some of the methods that really show the power of the IO data type are really hard to discover for newcomers, for example:
- run these two actions in parallel
- schedule this IO for later
This PR adds a couple of methods:
- right and left shark (seriously, it's really good to make them very visible!)
- `&>`, `<&`, `parProduct`
- `delayBy`
- `as` (with a lazy parameter, which is an improvement over the functor syntax anyway)
- `io.option` (catching throwables to options), `IO.none[A]: IO[Option[A]]`, `IO.fromOption`
I also noticed the methods we already have aren't really sorted, so as another PR I'd like to order them alphabetically (there were no symbolic methods so I put the operators at the end).
I'm aware this will …
=> Add a bunch of useful functions directly on IO

core/shared/src/main/scala/cats/effect/Resource.scala
As far as I could see, in the current form it's only used to satisfy the same constraint when calling `mapK` recursively.
I added an overload and made the old one private, so code outside of CE shouldn't be hit with any incompatibility. I had to merge the argument lists to reduce the ambiguity locally, but it compiles to the same signature in JVM bytecode, so we should be good.
=> Remove Bracket constraint from Resource.mapK

site/src/main/mdoc/tutorial/tutorial.md
In the https://typelevel.org/cats-effect/tutorial/tutorial.html webpage, a link redirecting to IO data type documentation is wrong (due to an issue on benbalter/jekyll-relative-links#61 )
=> Tutorial webpage : fix link to IO data type URL

core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/SyncIO.scala
Swapping wording to match `recover` (error) and then `map` (success)
=> Docs: swap wording to convey correct intent

core/js/src/main/scala/cats/effect/internals/IOAppPlatform.scala
Fixes https://github.com/typelevel/cats-effect/issues/838 by checking if `global.process` exists before attempting to set the `exitCode`.
=> Avoid exception when using IOApp in browsers.

core/shared/src/main/scala/cats/effect/IO.scala, core/shared/src/main/scala/cats/effect/Sync.scala
`ApplicativeError.redeem` and `MonadError.redeemWith` have been added in Cats, by @travisbrown in https://github.com/typelevel/cats/pull/3146, might as well take advantage of it by overriding the methods in our instances.
NOTE: for `EitherT`, `OptionT`, etc, these should be overridden in Cats, if they aren't already.
=> Optimize redeem/redeemWith in instances

core/shared/src/main/scala/cats/effect/Clock.scala, laws/shared/src/test/scala/cats/effect/TimerTests.scala
The default from Timer is the least specific.
But it was defined in a subtype and hence ambiguous.
To fix that move it to a supertype.
In an ideal world (Scala 2.13) we would not need any low priority traits.
But a bug in Scala 2.12 causes it to turn a blind eye to higher-kinded specificity.
Fixes #784
=> Fix resolution of Clock implicits

core/shared/src/main/scala/cats/effect/Bracket.scala, core/shared/src/test/scala/cats/effect/SyntaxTests.scala
This enables the smooth usage of `Bracket` syntax on monad transformers in cases where a `Sync` instance is present. See #806 for background
=> Add implicit proxies for transformers in Bracket

build.sbt, core/shared/src/main/scala/cats/effect/concurrent/MVar.scala, core/shared/src/main/scala/cats/effect/internals/MVarAsync.scala, core/shared/src/main/scala/cats/effect/internals/MVarConcurrent.scala, core/shared/src/test/scala/cats/effect/concurrent/MVarTests.scala, laws/jvm/src/test/scala/cats/effect/MVarJVMTests.scala, site/src/main/mdoc/concurrency/mvar.md
Motivation:
I found an open good first issue #732 while reading about `MVar`. This branch contains an attempt to implement it.
Modification:
- add `tryRead: F[Option[A]]` similar to [Control-Concurrent-MVar#tryRead](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Concurrent-MVar.html#v:tryReadMVar)
- add a test and a line into the docs
I wonder does it do what is it intended to do? I am happy to amend it if I've missed something, suggestions are welcome. Thank you!
=> MVar: add "tryRead" fixes #732

core/shared/src/main/scala/cats/effect/Resource.scala, core/shared/src/test/scala/cats/effect/ResourceSyntax.scala
Would also appreciate a look from @neko-kai. I think this works around the issue. It's a little annoying, but I wasn't able to find anything more elegant, and the nice thing is that it doesn't touch binary compatibility. I *believe* it should also be fully source-compatible with all existing call-sites that weren't already broken.
Fixes #807 (I think)
=> Implemented very silly workaround for #807

core/shared/src/main/scala/cats/effect/concurrent/Ref.scala, core/shared/src/test/scala/cats/effect/concurrent/LensRefTests.scala
I find `Ref.lens` useful in tests, where a single `Ref` aggregating state of multiple mocks can be transformed into a few "focused" `Refs`, ready for use in the mocks.
I'm not sure, though, if it should be a part of `cats-effect` or rather some small satellite library, so I'll leave it up to you to decide :wink:
=> Add Ref.lens constructor

core/shared/src/main/scala/cats/effect/concurrent/Ref.scala
Make it explicit that it's the previous value that is returned. To me at least, it's ambiguous whether "the value that was updated" refers to the new updated value or the previous one.
```
@ val r = Ref.unsafe[IO, Int](0)
r: Ref[IO, Int] = cats.effect.concurrent.Ref$SyncRef@11eed657
@ r.getAndUpdate(_ + 1).unsafeRunSync
res0: Int = 0
@
```
=> Update scaladoc for Ref.getAndUpdate

build.sbt, src/main/scala/ce3/Outcome.scala, src/test/scala/ce3/laws/Generators.scala, src/test/scala/ce3/laws/OutcomeSpec.scala, src/test/scala/ce3/laws/PureConcSpec.scala
This is just an idea, but I noticed all of the generators only use the constructors / methods provided by the type class, the only thing that needs something more (`run`) being the `Cogen` instance.
Pushing this further would involve splitting the class into generators for monads, monaderrors, brackets, concurrents... which might or might not be easy to encode in Scala, but if it's possible - might give us a lot of niceness (e.g. generators for the Concurrent part of Resource, when it's available) for a very low cost.
Maybe we could use an encoding similar to what we do with laws extending from each other.
=> CE3: Reusable generators

core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala
In the current `IORunLoop.step` implementation, the compiler boxes `currentIO`, `bFirst`, `bRest` and `unboxed` in an `ObjectRef` because they are all mutable variables that are captured in a lambda. This degrades performance for certain programs, particularly all `SyncIO` programs and all `IO` programs before they encounter the first asynchronous boundary (that are run with `unsafeRunSync`).
I only had enough patience to run the `DeepBindBenchmark` and `ShallowBindBenchmark`, whose results are shown below. Benchmarks were run on a MacBook Pro 15" 2015. Most of the other benchmarks probably see improved performance as well, but I talk more about that later.
```
[info] Benchmark                   (size)   Mode  Cnt     Score    Error  Units
[info] ShallowBindBenchmark.async   10000  thrpt …
```
=> Eliminate boxing in IORunLoop.step

core/shared/src/main/scala/cats/effect/concurrent/Ref.scala, core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala
Add combinators that allow for short-circuit behavior in CAS retry loops. This is useful when you want to perform an atomic state transition under specific conditions, but if those conditions aren't met, terminate early so no extra contention is placed on the atomic.
Maybe there's room for expressing some of the existing combinators in terms of these new ones. I could also see an `updateMaybe` or `modifyMaybe` that just take a `A => Option[A]`.
=> Ref#modifyOr and Ref#updateOr

README.md, build.sbt, site/src/main/resources/microsite/_config.yml
Fix #848: Correct configuration of jekyll-relative-links plugin to ensure .md links are converted to .html links when the microsite is built.
Fix #883: Specify basepath when serving microsite locally (`-b /cats-effect`) so it renders correctly. Also, added info about using the provided Gemfile to install jekyll and required plugins.
=> Fix #848 and #883: broken links in the documentation and missing basepath when running microsite locally

build.sbt, core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala, core/shared/src/main/scala/cats/effect/internals/LinkedLongMap.scala, core/shared/src/main/scala/cats/effect/internals/MVarConcurrent.scala, core/shared/src/test/scala/cats/effect/internals/LinkedLongMapTests.scala
@johnynek came on Gitter the other day and found that the `Deferred` implementation was consuming a surprising amount of CPU on an app (chat logs are [here](https://gitter.im/typelevel/cats-effect?at=5f0644d68342f4627402286a)). It turns out that the `hashCode` method for the `Id` class that `Deferred` uses to uniquely index callbacks in the `get` method is pretty costly.
The revised implementation here uses the `AtomicReference` state field to track an extra `Long` that serves as a monotonic counter to uniquely index `get` callbacks. `MVarConcurrent` has similar details in its implementation, so I also changed that one. Both `Deferred` and `MVarConcurrent` use a `LinkedMap` under the hood, but only ever uses `Long`s as keys. However since they're the only two clients of that class, I …
=> Revise Deferred, MVarConcurrent, LinkedMap

core/shared/src/main/scala/cats/effect/IO.scala
map2Eval is often used when we want to recurse on the right hand side. The default implementation just calls `.map` on the Eval forcing the full evaluation to happen before we can return the `IO` instance.
We can instead just call `.value` once the `A` value from `fa` has been produced which can result in occasionally doing less work when `fa` is a failure, or never completes.
=> Implement map2Eval for IO
